version: '3.9'

services:

  web:

    image: YOUR_DOCKERHUB_USERNAME/webapp:latest

    container_name: webapp

    restart: always

    ports:
      - "8000:8000"

    environment:

      FLASK_ENV: production
